#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x udiskie > /dev/null || udiskie &

bspc monitor DVI-I-2 -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          20
bspc config split_ratio			0.5
bspc config borderless_monocle	true
bspc config gapless_monocle 	true
bspc config normal_border_color	'#2e3440'
bspc config active_border_color	'#2e3440'
bspc config focused_border_color	'#3b4252'
bspc config presel_feedback_color	'#3b4252'

/usr/lib/xfce-polkit/xfce-polkit &


picom &
$HOME/.screenlayout/display.sh
~/.fehbg &
xsetroot -cursor_name left_ptr
eww open bar
wmname LG3D
thunar --daemon &
